export const CONTEXTS = {
  generate: "generate",
  init: "init",
  prodDependencies: "production dependencies",
  devDependencies: "dev dependencies",
  npmInit: "npm init",
  commitLint: "commitlint",
  swagger: "swagger",
  tsconfig: "tsconfig",
  husky: "husky",
  git: "git",
  prompter: "prompter",
  projectName: "projectName",
  controller: "controller",
  service: "service",
};
